config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # users
  get 'profile' => 'users#profile'
  devise_for :users

  # events
  resources :events
  resources :invites, only: [:index, :create]
  post 'confirmation/:id' => 'invites#confirm', as: 'confirmation'

  # static_pages and sessions
  root 'static_pages#home'
  get 'dashboard' => 'static_pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  scope :newest, -> { order('date desc') }
  belongs_to :creator, class_name: 'User'

  has_many :invites, foreign_key: :attended_event_id
  has_many :attendees, through: :invites, source: :attendee

  validates :name, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 5 }
  validates :date, presence: true
  validate  :cannot_be_past_today

  self.per_page = 20

  private

  def cannot_be_past_today
    return if date.blank? || date.nil?
    errors.add(:date, "can't be past today!") if date.to_date < Time.now.to_date
  end
end

app/models/invite.rb
class Invite < ApplicationRecord

  before_create :set_peding
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  def confirm_invite
    update_attribute :status, 'Confirmed'
  end

  private

  def set_peding
    self.status = 'Pending'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, :foreign_key => "creator_id", :class_name => "Event"

  has_many :invites, :foreign_key => "attendee_id"
  has_many :attended_events, through: :invites, :source => :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(events_params)
    if @event.save
      flash[:success] = 'Event created'
      redirect_to @event
    else
      flash.now[:danger] = 'Failed to create event'
      render :new
    end
  end

  def index
    @events = []
    @events = current_user.events.paginate(page: params[:page]).newest unless current_user.nil?
  end

  def show
    @event = Event.find(params[:id])
    @invites = Invite.eager_load(:attendee).where(attended_event_id: @event.id)
  end

  def destroy
    @event.destroy
    flash[:success] = 'Event deleted with success'
    redirect_to request.referrer || root_url
  end

  def edit
    @event = Event.includes(:invites).find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(events_params)
      flash[:success] = 'Event updated'
      redirect_to @event
    else
      flash.now[:danger] = 'Failed to update event'
      render :edit
    end
  end

  private

    def events_params
      params.require(:event).permit(:name, :date, :description)
    end

    def correct_user
      @event = current_user.events.find_by(id: params[:id])
      redirect_to request.referrer || root_url if @event.nil?
    end



end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!

  def create
    @service = CreateInvite.new params[:invite][:event_id], current_user
    @service.invite params[:invite][:email]
    @invite = @service.invitation
    respond_to { |format| format.js }
  end

  def confirm
    @invite = Invite.find_by(id: params[:id])

    unless invite_belongs_to_current_user @invite
      flash[:danger] = "This invite doesn't belongs to you"
      redirect_to request.referer || events_path
    end

    if @invite.confirm_invite
      respond_to { |format| format.js }
    else
      redirect_to request.referer || events_path
    end
  end

  def index
    @invites = current_user.invites.paginate page: params[:page] unless
      current_user.nil?
  end

  private

  def load_event(event)
    @event = event
    @invites = Invite.eager_load(:attendee).where(attended_event_id: @event.id)
  end

  def invite_belongs_to_current_user(invite)
    invite.attendee.id == current_user.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController  
  before_action :authenticate_user!, only: :dashboard

  def home
    redirect_to dashboard_path if user_signed_in?
  end

  def dashboard
    @events = current_user.events.last(4)
    @invites = current_user.invites.last(4)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user?, only: :profile

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    redirect_to root_path if @user.nil?

  end

  def profile
    @user = User.find_by(id: current_user.id)
  end


  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def event_date(date)
    date.strftime("%d/%m/%Y")
  end

  def can_edit?(event)
    event.creator.id == current_user.id
  end
  
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def user_logged
    redirect_to root_url unless logged_in?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_events_list.html.erb
<div style="margin-top: 15px;">
  <%= render 'shared/events', object: @events %>
  <%= will_paginate @events %>
</div>

app/views/events/_form.html.erb
<div style="margin-top: 20px !important">
  <%= form_for(@event) do |f| %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :date %>
          <%= f.date_field :date, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-success" %>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>
<% if can_edit? @event %>
<div style="margin-top: 15px; !important">
    <%= render partial: 'invites/invite', locals: {event_id: @event.id}%>
</div>
<% end %>

app/views/events/index.html.erb
<% if @events.any? %>
    <%= render 'events_list' %>
<% else %>
    <h3 class="text-center text-muted"> There are no events </h3>
<% end %>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<div class="page-header">
    <h1> 
        <%= @event.name %> <small style="float:right;">When: <%= event_date @event.date %></small> 
    </h1>
</div>

<div>
    <p>Created by: <%= @event.creator.email %></p>
</div>

<div>
    Event details:
    <div class="form-group">
        <%= text_area_tag :description,  @event.description, disabled: true, class: 'form-control', rows: '10' %>    
    </div>     
</div>

<% if can_edit? @event %>
    <div style="margin-top: 15px; !important">
        <%= render partial: 'invites/invite', locals: {event_id: @event.id}%>
    </div>
<% end %>

<br/>

<p>Who is going?</p>

<div id="invites">    
    <%= render 'invites/invitations', invites: @invites %>    
</div>

app/views/invites/_error_messages.html.erb
  <div class="alert alert-dismissible alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <% object.each do |error| %>
        <%= error %><br/>
    <% end %>
  </div>

app/views/invites/_invitation.html.erb
<div class="event-invite">
    <div class="event-invite-image">
        <%= image_tag 'avatar.png', size: '50x50', class: 'img-responsive'%>
    </div>
    <div class="event-invite-content">                  
        <%= invite.attendee.email  %> <br/>
        <span id="invite-<%=invite.id%>">
            <%= invite.status %>
        </span> 
        <% if invite.status == 'Pending' && invite.attendee.id == current_user.id %>                        
            <%= link_to "Confirm", confirmation_path(invite), method: :post,
                        remote: true, class: 'event-invite-confirmation' , id: 'bt-invite-'+invite.id.to_s  %>              
        <% end %>      
    </div>        
</div>    

app/views/invites/_invitations.html.erb
<% invites.each do |invite| %>
    <div class="event-invite">
        <div class="event-invite-image">
            <%= image_tag 'avatar.png', size: '50x50', class: 'img-responsive'%>
        </div>
        <div class="event-invite-content">                  
            <%= invite.attendee.email  %> <br/>
            <span id="invite-<%=invite.id%>">
                <%= invite.status %>
            </span> 
            <% if invite.status == 'Pending' && invite.attendee.id == current_user.id %>                        
                <%= link_to "Confirm", confirmation_path(invite), method: :post,
                            remote: true, class: 'event-invite-confirmation' , id: 'bt-invite-'+invite.id.to_s  %>              
            <% end %>      
        </div>        
    </div>                  
<% end %>

app/views/invites/_invite.html.erb
<%= form_for(:invite, url: invites_path, method: 'post', html: {class: "form-inline"}, remote: true ) do |f| %>
  <%= f.hidden_field :event_id, :value => event_id %>
  <div class="form-group">
    <%= f.label :email, "Email:" %>
    <%= f.text_field :email, class: "form-control", id: "invite_input" %>
  </div>
  <div class="form-group">
    <%= f.submit "Invite", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/invites/confirm.js.erb
$("#invite-<%= @invite.id %>").text("Confirmed");
$("#bt-invite-<%= @invite.id %>").remove();

app/views/invites/create.js.erb
<% if @service.created?%>
    $("#invites").append("<%= escape_javascript  render 'invitation', invite: @invite %> ");
<% else %>
    $("#main-container").prepend(" <%= escape_javascript render 'error_messages', object: @service.errors %> ");
<% end %>

app/views/invites/index.html.erb
<% if @invites.any? %>
  <div class="container" style="margin-top: 50px">
    <table class="table table-striped">
      <tr>
        <th>Event</th>
        <th>Date</th>
        <th>Description</th>
        <th>Status</th>
      </tr>
      <% @invites.each do |invite| %>
        <tr>
          <td><%= link_to invite.attended_event.name, invite.attended_event %></td>
          <td><%= event_date invite.attended_event.date %></td>
          <td><%= invite.attended_event.description[0..50] %></td>
          <td><%= invite.status %></td>          
        </tr>
      <% end %>
    </table>
    <%= will_paginate @events %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event Track</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div style="margin-top: 55px">
    <main class="container" id="main-container">
        <%= render 'shared/messages' %>  
        <%= yield %>      
    </main>      
  </div>
</body>
</html>

app/views/shared/_events.html.erb
<% if object.any? %>
  <div class="row">
    <% object.each do |event| %>
      <div class="col-md-3 col-sm-6 event-card">
          <div class="">
          <div class="event-card-image">
            <%= image_tag 'event-placeholder.png', alt: 'Event placeholder', class: 'img-responsive' %>          
          </div>
          <div class="event-card-title">
            <%= link_to event.name, event %>
          </div>
          <% if can_edit? event %>
            <div class="event-card-bottom">
              <span class="pull-left event-card-bottom-invites"><%= pluralize(event.invites.count, "Person") %> Invited</span>
              <span class="pull-right"><%= link_to "Edit", edit_event_path(event), class: "btn btn-primary event-card-bottom-btn" %></span>          
            </div>                      
          <% end %>
        </div>        
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_invited_events.html.erb
<% if object.any? %>
  <div class="row">
    <% object.each do |invite| %>
      <div class="col-md-3 event-card">
        <div class="">
          <div class="event-card-image">
            <%= image_tag 'event-placeholder.png', alt: 'Event placeholder', class: 'img-responsive' %>            
          </div>
          <div class="event-card-title">
            <h3><%= link_to invite.attended_event.name, event_path(invite.attended_event) %></h3>
          </div>        
          <div class="event-card-bottom">
            <span class="pull-left event-card-bottom-invites" id="invite-<%=invite.id%>">Invite: <%= invite.status %></span>
            <% if invite.status == 'Pending' %>
              <span class="pull-right event-card-bottom-btn">
                <%= link_to 'Accept invite', confirmation_path(invite), class: 'btn btn-success', 
                            remote: true, method: :post, id: 'bt-invite-'+invite.id.to_s %>
              </span>
            <% end %>
          </div>
        </div>
      </div>        
    <% end %>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |key,msg| %>
  <% if key == 'notice' %>
    <% alert = "info" %>
  <% else %>
    <% alert = key %>
  <% end %>

  <div class="alert alert-dismissible alert-<%=alert%>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"> Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>"><strong>Event Track</strong></a>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Create a new Event", new_event_path %></li>
        </ul>
      <% end %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
              <span class="caret"></span>
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", '#' %></li>
                <li><%= link_to "Logout", destroy_user_session_path , method: :delete %></li>
              </ul>
          </li>
        <% else %>
          <li>
            <form class="navbar-form navbar-right">
              <%= link_to "Login", new_user_session_path, class: "btn btn-success" %>
            </form>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/dashboard.html.erb
<h1>
    Events I've created: <span class="pull-right"><%= link_to "My events", events_path, class: 'btn btn-success' %></span>
</h1>

<% if @events.any? %>
    <%= render 'shared/events', object: @events %>
<% else %>
    <h4 class="text-center text-muted">You haven't created any event, <%= link_to 'click here', new_event_path %> and create one now</h4> 
<% end %>
<hr class="featurette-divider">

<h1>
    Events I'm invited: <span class="pull-right"><%= link_to "My Invites", invites_path, class: 'btn btn-success' %></span> 
</h1>

<% if @invites.any? %>
    <%= render 'shared/invited_events', object: @invites %>
<% else %>
    <h4 class="text-center text-muted">You aren't going anywhere </h4>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron" style="background-color: #72B095 !important">
    <div class="row">
        <div class="col-md-4">
            <%= image_tag 'EventTrack-logo.png', alt: 'EventTrack logo that looks like a callendar', class: 'img-responsive', style:'margin: 0 auto;' %>
        </div>
        <div class="col-md-6 col-offset-4">
            <br><br>
            <span class="text-left">
                <p>Create events, invite your friends, and party hard.<br/>
                    Don't have an account? No problem.<br> <%= link_to "Register", new_user_registration_path, class: "btn btn-primary" %></p>
            </span>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Create</h2>
            <p>
                That's right, you can create any event you want.</br>
                Party, Barbcue, Meetup, just register and create it!
            </p>
        </div>
        <div class="col-md-4">
            <h2>Invite</h2>
            <p>
                You can invite everybody.</br>
                Your friends, your girlfriend, yo brotha,</br>
                you sista, and yo mama too.
            </p>
        </div>
        <div class="col-md-4">
            <h2>Share</h2>
            <p>Because everyone in the internet must know about it</p>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br/>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/users/profile.html.erb
<div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
    </a>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-header">
  <h3><%= @user.id %> - <%= @user.username %></h3>
</div>
Events I've created:
<% if @user.events %>
    <%= render 'shared/events', object: @user.events %>
<% else %>
  <h4 class="text-center text-muted">This user doesn't have any event</h4>
<% end %>

Events I'm going:
<% if @user.attended_events.any? %>
  <%= render 'shared/events', object: @user.attended_events %>
<% else %>
  <h4 class="text-center text-muted">This user isn't going anywhere</h4>
<% end %>